server:
  port: 8000

spring:
  #开启redis缓存
  redis:
#    cluster:
#      nodes: redis-cluster01.test.geely.com:6395,redis-cluster03.test.geely.com:6395,redis-cluster05.test.geely.com:6394
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 100
        min-idle: 10
    timeout: 60000ms
    host: 127.0.0.1
    password: geely

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3386/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.190.38.178:1521:geely
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3386/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    hikari:
#      pool-name: DateHikariCP
#      minimun-idle: 5
#      idle-timeout: 1800000
#      maximun-pool-size: 10
#      auto-commit: true
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/sql-mappers/*.xml
  type-aliases-package: com.example.seckill.model

#日志打印(错误信息)
logging:
  level:
    com.example.seckill.model: debug

